### ISSUE TITLE
setValue() is appending the value instead of replacing the value - seems to be only when forms load via ajax calls

### ISSUE THREAD

**Issue by davidkalec** [minkphp/Mink#804] opened 2021-06-02 18:59 UTC
This started happening more recently. I'm currently on ChromeDriver-v91
When a value is pulled onto a form via AJAX and I use ->setValue(), this is appending the value. I echoed getValue() on the field, and it is showing "" instead of the actual value in the form field.

Page takes the following action:
- page loads
- Behat selects a user from a drop down menu
- Form fields load with that user's details via an ajax call
- Behat then attempts to update the user's username and email, but it is actually appending the value
- - getValue() prior to setting the value is showing "" 
- - I added longer wait times before this step, just to see if behat needed extra time in order to access the data; but didn't solve the issue.

This was working with ChromeDriver-v85

**Comment by aik099** [comment] 2021-06-04 19:04
> This was working with ChromeDriver-v85

* In that case, it would be better to report issues in their repo as well.
* If that works in older Google Chrome versions or even on the latest Firefox, then the issue is with ChromeDriver and not the Mink.

**Comment by stof** [comment] 2023-11-29 12:49
I'm closing this issue as it is about a non-official driver. The issue should be reported to their team.

**Closed by stof** 2023-11-29 12:49 UTC
