### ISSUE TITLE
1.8.0/1.8.1 releases break `dmore/chrome-mink-driver`

### ISSUE THREAD

**Issue by mpdude** [minkphp/Mink#798] opened 2020-03-12 13:41 UTC
`dmore/chrome-mink-driver` is a driver for using a headless Chrome browser. This driver has the special requirement that it needs to connect to the running Chrome instance to pass it request headers, cookie values etc., possibly before opening (`visit()`ing) pages.

All this happens from within the driver's `start()` method: https://gitlab.com/DMore/chrome-mink-driver/-/blob/master/src/ChromeDriver.php#L70-72

Now since #705 was merged here (and released only earlier today), this call to `start()` is postponed. That means that calls to `\Behat\Mink\Session::setRequestHeader()` or `\Behat\Mink\Session::setCookie()` will fail.

I know too little about the contracts between Mink and the drivers to tell if this is an implementation flaw in the driver or a BC break in Mink.

Anybody with a better understanding please advise where this should be fixed.

Issue for the driver: https://gitlab.com/DMore/chrome-mink-driver/-/issues/94

/cc @DorianCMore

**Comment by stof** [comment] 2020-03-12 14:55
Can you provide the reproducing case (your usage of Mink that was working before and does not work anymore) ?

**Comment by mpdude** [comment] 2020-03-17 07:37
```php
<?php

use Behat\Behat\Hook\Scope\BeforeScenarioScope;
use Behat\MinkExtension\Context\RawMinkContext;

class MyAppContext extends RawMinkContext ...
{
    /**
     * @BeforeScenario
     */
    public function setUpBeforeScenario(BeforeScenarioScope $scope)
    {
        // Workaround for https://github.com/minkphp/Mink/issues/798:
        $this->getSession()->start();

        // $this->getSession()->setCookie() fails as of minkphp/Mink ^1.8
        if (\function_exists('xdebug_is_debugger_active') && xdebug_is_debugger_active()) {
            $this->getSession()->setCookie('XDEBUG_SESSION', 'behat');
        }
    }

    ....
```

**Comment by lpeabody** [comment] 2020-03-18 17:15
For additional context, see https://travis-ci.com/github/lpeabody/Metis/builds/153721427#L1377 for an example of where this breaks. `$this->page` evaluates to `null` here https://gitlab.com/DMore/chrome-mink-driver/-/blob/2.7.0/src/ChromeDriver.php#L1058.

It's broken out more verbosely here https://gitlab.com/DMore/chrome-mink-driver/-/issues/94.

**Comment by aik099** [comment] 2020-03-19 07:57
@mpdude , actually I see no issue here.

In Selenium (which emulates user actions) you can't set a cookie on a page prior to that page being visited. Same goes for `dmore/chrome-mink-driver` driver, which does the same as Selenium, but without Selenium in Google Chrome.

Setting headers (e.g. basic authentication, cookies, etc.) prior to page visiting is only possible in headless drivers, like `MinkBrowserKitDriver` and `MinkZombieDriver`. 

The solution you came up with is correct way to do this. I'm not sure why it even worked, because you've set cookie right after browser window was opened, but prior to page being visited. In that case there is no way to determine at which URL cookie should apply.

**Comment by mpdude** [comment] 2020-03-19 08:30
But I should be able to set a request header before requesting a page, right?

**Comment by aik099** [comment] 2020-03-19 17:39
> But I should be able to set a request header before requesting a page, right?

@mpdude , I guess no. If you can't do this with Selenium you can't do it in driver, that controls actual web browser.

**Comment by mpdude** [comment] 2020-03-19 17:58
I am not sure if we're talking about the same thing: The driver needs the `start()` method to be called so it connects to the browser. But once that's done, you _can_ add the cookies and/or headers, even before visiting the page.

Am I missing something?

**Comment by aik099** [comment] 2020-03-23 19:30
If that is how it works for that driver then it's good thing. It doesn't work that way with other drivers.

Maybe driver code needs to be updated to that it auto-starts session, when it's missing and somebody is attempting to set cookies.

**Comment by mpdude** [comment] 2020-03-24 07:47
@aik099 I cross-posted this as an issue here and over at the driver's repo at https://gitlab.com/DMore/chrome-mink-driver/-/issues/94 because I know too little about the _contracts_ between Mink and the drivers and I was unsure if this needs to be fixed in the driver or here.

https://github.com/minkphp/Mink/blob/07c6a9fe3fa98c2de074b25d9ed26c22904e3887/src/Driver/DriverInterface.php#L32-L51

> Calling any action before visiting a page is an undefined behavior. 
> The only supported method calls on a fresh driver are [...]
> - setRequestHeader()

If "fresh" means "not started", then probably the driver should _not_ rely on `start()` being called until the very last moment before `visitPage()`?

**Comment by adorin** [comment] 2020-03-24 13:52
> @mpdude , I guess no. If you can't do this with Selenium you can't do it in dmore/chrome-mink-driver driver, that controls actual web browser.

Selenium needs the browser to navigate to the cookie domain before being able to set a cookie. The chrome driver can technically set the cookie to base_url before visiting it, as long as ->start() is called before setCookie.

But since calling setCookie() before visit() is undefined behaviour, that doesn't have much practical value.

> Maybe driver code needs to be updated to that it auto-starts session, when it's missing and somebody is attempting to set cookies.

It's possible, but is it a good idea? What if mink called stop() specifically and then we just overrule that with autostart. We'd essentially be taking control over start/stop/reset.

**Comment by aik099** [comment] 2020-03-26 19:47
Closing as @DorianCMore agreed to fix it on driver side in https://gitlab.com/DMore/chrome-mink-driver/-/issues/94.

**Closed by aik099** 2020-03-26 19:47 UTC

**Comment by lpeabody** [comment] 2020-03-27 16:17
I'm failing to see where he has explicitly agreed to fix this in chrome-mink-driver?

**Comment by aik099** [comment] 2020-03-29 12:22
@lpeabody , here is a screenshot with relevant text selected from GitLab:

![GitLab_DMore_chrome-link-driver_issue94_comment](https://user-images.githubusercontent.com/1277526/77848987-1d2fd900-71d1-11ea-95af-955d1c98656f.png)

**Comment by xurizaemon** [comment] 2020-10-05 03:14
There's an MR for this at https://gitlab.com/DMore/chrome-mink-driver/-/merge_requests/93 now.

Input / feedback welcome - @aik099 I'd especially welcome your thoughts on the solution, I'm pretty fresh to this!

**Comment by mpdude** [comment] 2020-10-07 13:44
https://gitlab.com/DMore/chrome-mink-driver/-/merge_requests/93 does not fix the issue:

It fixes that you can set HTTP Basic Auth and/or request headers before calling `visit()`, but it does not fix calls to `setCookie()`.

You still can call the `start()` method on the driver yourself and afterwards call `setCookie()`, even before calling `visit()`. 

I find it hard to understand why `setCookie()` should not be possible when `setRequestHeader()` is. But that might be because `setCookie()` is expected to have additional semantics (setting the cookie in the context of a page limits it to... the URL? Domain?) over just a "plain" request header.

**Comment by aik099** [comment] 2020-10-22 18:15
@xurizaemon , I've commented on that PR on GitLab website.
