### ISSUE TITLE
getAttribute return WebDriver\Execute Object instead of value

### ISSUE THREAD

**Issue by Nikonovaa** [minkphp/Mink#750] opened 2017-11-28 17:15 UTC
I use Appium+Selenium2+Behat+Mink, but when I try to get attribute by the following code:

```
$id = $this->getSession()->getPage()->find('xpath', $xpath)->getAttribute("id");
```

I get something like this:

```
WebDriver\Execute Object
        (
            [url:protected] => 0.0.0.0:4723/wd/hub/session/b1892305-af0b-4bf3-a197-3f58d5ef6954/execute
        )
```

What possible can be wrong?

**Comment by aik099** [comment] 2017-11-28 19:06
1. What is the expected value in this case?
2. The problem can be in either of these places:

* Appium telling something not expected by WebDriver protocol
* https://github.com/instaclick/php-webdriver not process stuff coming from Appium
* this library not understanding response from https://github.com/instaclick/php-webdriver

These is not enough data at the moment to tell which of above scenarios is true.

I haven't used Appium with Mink, so I have no idea if it works to some extent at all.

**Comment by Nikonovaa** [comment] 2017-11-29 04:40
@aik099 Expected value - element's href:
`<a href="/booking/booking?&orgid=34"></a>`
but this problem repeats for any attribute.

**Comment by Nikonovaa** [comment] 2017-11-29 13:12
@stof 
```
alexandresalome/php-selenium        v1.1.0             PHP Library for Selenium
behat/behat                         dev-master 6377678 Scenario-oriented BDD framework for PHP 5.3
behat/gherkin                       v4.5.1             Gherkin DSL parser for PHP 5.3
behat/mink                          dev-master 9ea1ceb Browser controller/emulator abstraction for PHP
behat/mink-browserkit-driver        dev-master 1c9c8ad Symfony2 BrowserKit driver for Mink framework
behat/mink-extension                dev-master c85f327 Mink extension for Behat
behat/mink-goutte-driver            dev-master 7a4b2d4 Goutte driver for Mink framework
behat/mink-sahi-driver              dev-master 8636f8d Sahi.JS driver for Mink framework
behat/mink-selenium-driver          dev-master 5efe8a3 Selenium driver for Mink framework
behat/mink-selenium2-driver         dev-master 46404b0 Selenium2 (WebDriver) driver for Mink framework
behat/sahi-client                   dev-master edd87e8 Sahi.js client for PHP 5.3
behat/transliterator                dev-master 826ce7e String transliterator
container-interop/container-interop 1.2.0              Promoting the interoperability of container objects (DIC,...
fabpot/goutte                       dev-master db5c28f A simple PHP Web Scraper
guzzlehttp/guzzle                   6.3.0              Guzzle is a PHP HTTP client library
guzzlehttp/promises                 dev-master e9cdab6 Guzzle promises library
guzzlehttp/psr7                     dev-master d2537c8 PSR-7 message implementation that also provides common ut...
instaclick/php-webdriver            dev-master 85e7467 PHP WebDriver for Selenium 2
kriswallsmith/buzz                  v0.15.1            Lightweight HTTP client
psr/container                       dev-master 2cc4a01 Common Container Interface (PHP FIG PSR-11)
psr/http-message                    dev-master f6561bf Common interface for HTTP messages
psr/log                             dev-master 4ebe3a8 Common interface for logging libraries
symfony/browser-kit                 3.4.x-dev 179522b  Symfony BrowserKit Component
symfony/class-loader                dev-master 2141b76 Symfony ClassLoader Component
symfony/config                      3.4.x-dev 6c7f114  Symfony Config Component
symfony/console                     3.4.x-dev 0f859c4  Symfony Console Component
symfony/css-selector                3.4.x-dev 7134b93  Symfony CssSelector Component
symfony/debug                       3.4.x-dev 24b7bbf  Symfony Debug Component
symfony/dependency-injection        3.4.x-dev 578f167  Symfony DependencyInjection Component
symfony/dom-crawler                 2.8.x-dev eeb7809  Symfony DomCrawler Component
symfony/event-dispatcher            3.4.x-dev ca20b8f  Symfony EventDispatcher Component
symfony/filesystem                  3.4.x-dev 4e75c61  Symfony Filesystem Component
symfony/polyfill-mbstring           dev-master 2ec8b39 Symfony polyfill for the Mbstring extension
symfony/translation                 3.4.x-dev 34c2376  Symfony Translation Component
symfony/yaml                        3.4.x-dev 1456882  Symfony Yaml Component
```

**Comment by stof** [comment] 2017-11-29 14:11
The issue is that you use `instaclick/php-webdriver` dev-master, which is now the dev version of version 2 of the library (so not backward compatible). They forgot to update the branch alias immediately, which is why it was still considered to be 1.x in the past (and so matching the behat/mink-selenium2-driver requirement). In the meantime, they fixed their branch alias.
Run a composer update for this package to force it to use the compatible version instead.

**Comment by stof** [comment] 2017-11-30 10:39
I'm closing this issue because the problem does not come from Mink or MinkSelenium2Driver, but from an incompatible version of `instaclick/php-webdriver` being used in the project (due to a mistake on their side which has been fixed in the meantime).

Btw, this allowed me to identify a bug in their dev version (without this bug, you would not have been affected either because the version 2 still supports the legacy protocol).

**Closed by stof** 2017-11-30 10:39 UTC

**Comment by Nikonovaa** [comment] 2017-11-30 11:11
@stof Thanks for the help, now it works :)
