### ISSUE TITLE
Can't follow link without href

### ISSUE THREAD

**Issue by JonRiv** [minkphp/Mink#674] opened 2015-09-22 14:19 UTC
Hello,

I'm not sure if it is rather a bug or an implicit behavior. But one cannot *follow* links without an href attribute. My main concern is the error message which is not explicit.

- browser : phantomjs
- application : react + material

- HTML element
```<a title="FollowMe">Example</a>```

- Behat step
> When I follow "FollowMe"

- Return error :
> Link with id|title|alt|text "FollowMe" not found.

Although it is in the document. Maybe a precision regarding the presence or miss of the href attribute would help.

Thank you !

**Comment by aik099** [comment] 2015-09-22 14:34
What driver are you using? If that's BrowserKitDriver, then you can't follow link without URL due this being headless driver that doesn't actually render the page.

**Comment by stof** [comment] 2015-09-22 14:47
We actually require links to have an ``href`` when locating links: https://github.com/minkphp/Mink/blob/0a2789063c86e49ae3640efd36fb13e525765410/src/Selector/NamedSelector.php#L71

And this is logical: ``<a>`` without an href is not a link, it is an anchor (used as target of in-page links). Note that a browser won't mark such anchors as link either (hovering them will not give you a pointer cursor for instance, unless you have your own CSS doing it).

Telling you that the href attr is missing on the existing element would be quite hard: we would have to make a special case, remembering how our XPath was built originally and running a similar XPath without the href condition to report such error. This is not possible without a rewrite of most parts of Mink AFAICT.

**Comment by aik099** [comment] 2016-07-04 18:28
Closing, because this is expected behavior.

**Closed by aik099** 2016-07-04 18:28 UTC
